### ISSUE TITLE
loading problem with spigot paper and mohist

### ISSUE THREAD

**Issue by Batsave** [PingLaggerYT/TranslateX#5]
Hello, I was recently able to test your plugin/solution to translate the chat but I ran into a problem:
Each time you restart, the configuration files are reset.

Impossible to keep the deepl api keys in memory and therefore the plugin "disables"
I remain available to test modifications on our server!

PS: we run on an EGG called Mohist: This EGG allows us to work with forge mods and with spigot / paper plugins

**Comment by Djorr** [comment]
Issues with the config have been solved.
